# name: my CI

# on:
#   push:
#     branches: [ "master" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14x]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Run (pwd)
#         run: pwd

#       - name: Run a (npm insstall)
#         run: npm install

#       - name: Run a (npm run build)
#         run: npm run build

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@3.6.2
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} #secrets.ACCESS_TOKEN是项目配置的密钥
#           BRANCH: page # The branch the action should deploy to.
#           FOLDER: dist # The folder the action should deploy.
#           CLEAN: true # Automatically remove deleted files from the deploy branch

