name: my CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14x]
    steps:
      - name: Run (pwd)
        run: pwd

      - name: Run a (npm insstall)
        run: npm install
        
      - name: Run a (npm run build)
        run: npm run build
